version: '2'
volumes:
    node-red-data:
    node-red-test-data:
    influxdb-data:
services:
  influxdb:
    image: influxdb:1.8  # использование специфичной версии, проверьте доступность для ARM
    container_name: influxdb
    privileged: true
    volumes:
        - 'influxdb-data:/var/lib/influxdb'
    ports:
      - "8086:8086"
      - "8089:8089"
    restart: always

  telegraf:
    image: telegraf:1.14.5  # проверьте доступность версии для ARM
    container_name: telegraf
    network_mode: "host"
    privileged: true
    depends_on:
      - influxdb
    restart: always
    environment:
       - interval=60s
       - flush_interval=60s

  grafana:
    image: grafana/grafana:6.7.4  # проверьте доступность для ARM
    container_name: grafana
    ports:
       - "3000:3000"
    depends_on:
       - influxdb
    restart: always

  mqtt:
    image: eclipse-mosquitto:latest  # стандартный образ MQTT для ARM
    container_name: mqtt
    ports:
      - "1883:1883"

  mqtt-test:
    image: eclipse-mosquitto:latest
    container_name: mqtt-test
    ports:
      - "1884:1883"

  node-red:
    image: nodered/node-red:latest  # использование официального образа Node-RED
    container_name: node-red
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always

  node-red-test:
    image: nodered/node-red:latest
    container_name: node-red-test
    volumes:
       - 'node-red-test-data:/data'
    ports:
       - "1882:1880"
    depends_on:
        - mqtt-test
    restart: always

  nginx:
    image: nginx:stable-alpine  # использование образа nginx для ARM
    container_name: nginx
    depends_on:
      - grafana
      - node-red
      - node-red-test
    ports:
       - "80:80"
       - "443:443"
    restart: always
